server:
  port: 8081
  servlet:
    context-path: /feeling_admin
system:
  callBackUrl: http://odd.bhxcw.com/lizard2.1.7
  heading: http://oss.zzbhxc.com/admin%2FHeadportrait.jpg
  ossAddress: https://weinuoqinggan.oss-cn-beijing.aliyuncs.com
  sex: 1
  namePrefix: 维诺情感-
  sign: 这家伙很懒什么都没留下。。。
  isProd: false
spring:
  datasource:
    url: jdbc:mysql://47.111.121.204:3306/feeling_core?characterEncoding=utf8&serverTimezone=GMT&useSSL=true
    username: feeling_core
    password: p3nimkNS8BaTZrz7
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 999999999999
      max-request-size: 999999999999
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000ms
    database: 0
    password:
    jedis:
      pool:
        max-idle: 100
        max-wait: -1ms
        min-idle: 2
logging:
  config: classpath:config/log4j2-test.yml
mybatis-plus:
  mapper-locations: classpath:mapper/**.xml
  typeAliasesPackage: com.bing.mapper
  global-config.id-type: 5
  global-config.field-strategy: 2
  global-config.db-column-underline: true
  global-config.refresh-mapper: true
  global-config.capital-mode: true
oss:
  address: oss-cn-beijing.aliyuncs.com/
  accessKey: LTAI0oyc0pRQxso2
  accessSecret: iitc3uJoSMtMP79aKgSYWMDcJbYIOc
  bucketName: weinuoqinggan
  filePath: picture/
juhe :
  key: 12ab675a9b398a5331bb00b922724fe2
  url: http://v.juhe.cn/sms/send
  DEF_CHATSET: UTF-8
  DEF_CONN_TIMEOUT: 30000
  DEF_READ_TIMEOUT: 30000
  userAgent: "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.66 Safari/537.36"
tx :
  sendEmailAccount: 1916172575@qq.com
  sendEmailPassword: aotecgthptykdeah
  sendEmailSMTPHost: smtp.qq.com
wy:
  from: girlfriendisnull@163.com
  username: girlfriendisnull@163.com
  password: qw962453
  host: smtp.163.com
#auth
auth:
  wxAppId: wxc5ca1b129f8a30c9
  wxSecret: 10bdc66705328e981332265fc8891bf9
  qqRedirect: http://www.bhxcw.com/redirect?
  qqAppId: 101509062
  qqSecret: ae173563e5dbd2d79564a2538d0fe587
wx:
  pay:
    appId: wx4f08413bfc6bbe20
    mchId: 1547000081
    mchKey: 0IZJa1N6hgd6jjNtjWhYQ09Fq70aoQi2
    subAppId:
    subMchId:
    keyPath: D:\aaa\apiclient_cert.p12
    notifyUrl: www.liliubing.cn
alipay:
  dev: false #默认false,为true表示使用沙箱环境
  sign-type: RSA2 #签名算法
  app-id: #应用ID
  private-key: #应用私钥
  alipay-public-key: #支付宝公钥